SDKAppID: 1400327058
SDKAPPSecret: d45e1e4f7aeed80017105f1c639cd7f95e58c025a218bf57bba5d4e25c6b10e8
server:
  port: 40001
  terminal: ORG
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/tianyoukeji
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: org
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            acquireTriggersWithinLock: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
thumbnail:
  large:
    width: 1334
    height: 1334
  middle:
    width: 667
    height: 667
  small:
    width: 300
    height: 300    